---
ospf:
  process_id: "2"
  rid: 2.2.2.2
  networks:
    - number: 10.0.0.0
      wildcard: 0.0.0.3
      area: "0"
    - number: 10.0.0.4
      wildcard: 0.0.0.3
      area: "0"
    - number: 2.2.2.2
      wildcard: 0.0.0.0
      area: "22"
